@namespace
class SpriteKind:
    NPC1 = SpriteKind.create()
    selesai = SpriteKind.create()
    NPC2 = SpriteKind.create()
    NPC3 = SpriteKind.create()
    NPC4 = SpriteKind.create()
    NPC5 = SpriteKind.create()
    NPC6 = SpriteKind.create()

def on_on_overlap(sprite2, otherSprite2):
    global DialogMode
    DialogMode = True
    game.show_long_text("Dalam UUD NRI Tahun 1945 dari Pasal 27-Pasal 34 berisi tentang .... warga negara.",
        DialogLayout.BOTTOM)
    story.show_player_choices("Hak", "Kewajiban", "Tugas")
    if story.check_last_answer("Hak"):
        info.change_score_by(10)
        mySprite3.set_kind(SpriteKind.selesai)
    elif story.check_last_answer("Kewajiban"):
        info.change_score_by(-5)
    elif story.check_last_answer("Tugas"):
        info.change_score_by(-5)
    else:
        pass
    DialogMode = False
    pause(1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.NPC2, on_on_overlap)

def on_on_overlap2(sprite5, otherSprite5):
    global DialogMode
    DialogMode = True
    game.show_long_text("Apa contoh dari wujud hubungan aktif dari hubungan antara negara dengan warga negara ? ",
        DialogLayout.BOTTOM)
    story.show_player_choices("memberikan hak pilih dalam pemilu",
        "menaati peraturan lalu lintas ",
        "membayar pajak ")
    if story.check_last_answer("memberikan hak pilih dalam pemilu"):
        info.change_score_by(10)
        mySprite2.set_kind(SpriteKind.selesai)
    elif story.check_last_answer(" menaati peraturan lalu lintas "):
        info.change_score_by(-5)
    elif story.check_last_answer("membayar pajak "):
        info.change_score_by(-5)
    else:
        pass
    DialogMode = False
    pause(1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.NPC1, on_on_overlap2)

def on_on_overlap3(sprite, otherSprite):
    global DialogMode
    DialogMode = True
    game.show_long_text("Bagaimana sifat hubungan antara negara dan warga negara ?",
        DialogLayout.BOTTOM)
    story.show_player_choices("Hubungan yang bersifat pasif",
        " Hubungan yang bersifat monopoli",
        "Hubungan yang bersifat totalitas")
    if story.check_last_answer("Hubungan yang bersifat pasif"):
        info.change_score_by(-5)
    elif story.check_last_answer(" Hubungan yang bersifat monopoli"):
        info.change_score_by(-5)
    elif story.check_last_answer("Hubungan yang bersifat totalitas"):
        info.change_score_by(10)
        mySprite6.set_kind(SpriteKind.selesai)
    else:
        pass
    DialogMode = False
    pause(1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.NPC5, on_on_overlap3)

def on_on_overlap4(sprite4, otherSprite4):
    global DialogMode
    DialogMode = True
    game.show_long_text("Dibawah ini yang bukan merupakan asas hubungan warga negara dengan negara adalah...",
        DialogLayout.BOTTOM)
    story.show_player_choices("Pancasila ",
        "Pembukaan UUD 1945 alinea I dan II",
        "Pembukaan UUD 1945 alinea III dan IV")
    if story.check_last_answer("Pancasila "):
        info.change_score_by(-5)
    elif story.check_last_answer("Pembukaan UUD 1945 alinea I dan II"):
        info.change_score_by(10)
        mySprite5.set_kind(SpriteKind.selesai)
    elif story.check_last_answer("Pembukaan UUD 1945 alinea III dan IV"):
        info.change_score_by(-5)
    else:
        pass
    DialogMode = False
    pause(1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.NPC4, on_on_overlap4)

def on_on_overlap5(sprite3, otherSprite3):
    global DialogMode
    DialogMode = True
    game.show_long_text("Hak dan Kewajiban telah dicantumkan dalam UUD 1945 pasal. pasal berapa sajakah yang megatur mengenai hak dan kewajiban warga negara? ",
        DialogLayout.BOTTOM)
    story.show_player_choices("Pasal 25, 26, 27", "Pasal 30, 31, 32", "Pasal 27, 28, 30")
    if story.check_last_answer("Pasal 25, 26, 27"):
        info.change_score_by(-10)
    elif story.check_last_answer("Pasal 30, 31, 32"):
        info.change_score_by(-10)
    elif story.check_last_answer("Pasal 27, 28, 30"):
        info.change_score_by(30)
        mySprite4.set_kind(SpriteKind.selesai)
    else:
        pass
    DialogMode = False
    pause(1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.NPC3, on_on_overlap5)

def on_on_overlap6(sprite6, otherSprite6):
    global DialogMode
    DialogMode = True
    game.show_long_text("Menurut teori Marxis, bagaimana pandangan terhadap peran negara dalam hubungannya dengan kaum borjuis?",
        DialogLayout.BOTTOM)
    story.show_player_choices("Negara hanya alat masyarakat",
        "Negara memiliki kekuatan nyata",
        "Negara harus dikendalikan oleh kelompok borjuis")
    if story.check_last_answer("Negara hanya alat masyarakat"):
        info.change_score_by(30)
        mySprite7.set_kind(SpriteKind.selesai)
    elif story.check_last_answer("Negara memiliki kekuatan nyata"):
        info.change_score_by(-10)
    elif story.check_last_answer("Negara harus dikendalikan oleh kelompok borjuis"):
        info.change_score_by(-10)
    else:
        pass
    DialogMode = False
    pause(1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.NPC6, on_on_overlap6)

def on_overlap_tile(sprite7, location):
    game.over(True, effects.smiles)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.collectible_red_crystal,
    on_overlap_tile)

DialogMode = False
mySprite7: Sprite = None
mySprite6: Sprite = None
mySprite5: Sprite = None
mySprite4: Sprite = None
mySprite3: Sprite = None
mySprite2: Sprite = None
tiles.set_tilemap(tilemap("""
    level1
    """))
mySprite = sprites.create(img("""
        . . . . f f f f . . . . .
        . . f f f f f f f f . . .
        . f f f f f f c f f f . .
        f f f f f f c c f f f c .
        f f f c f f f f f f f c .
        c c c f f f e e f f c c .
        f f f f f e e f f c c f .
        f f f b f e e f b f f f .
        . f 4 1 f 4 4 f 1 4 f . .
        . f e 4 4 4 4 4 4 e f . .
        . f f f e e e e f f f . .
        f e f 5 8 8 8 8 5 f e f .
        e 4 f 8 8 8 8 8 8 f 4 e .
        e e f 9 9 9 9 9 9 f e e .
        . . . f f f f f f . . . .
        . . . f f . . f f . . . .
        """),
    SpriteKind.player)
mySprite2 = sprites.create(img("""
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff......ccc.
        .ffefbf44fbfeff....cddc.
        .ffefbf44fbfeff...cddc..
        .fee4dddddd4eef.ccddc...
        fdfeeddddd4eeffecddc....
        fbffee4444ee4fddccc.....
        fbf4f222222f1edde.......
        fcf.f222222f44ee........
        .ff.f445544f............
        ....ffffffff............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.NPC1)
mySprite3 = sprites.create(img("""
        ........................
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff..........
        .ffefbf44fbfeff.........
        .fee41fddf14eef.........
        fdfeeddddd4eff..........
        fbffee444edd4e..........
        fbf4f2222edde...........
        fcf.f22cccee............
        .ff.f44cdc4f............
        ....fffddcff............
        .....fddcff.............
        ....cddc................
        ....cdc.................
        ....cc..................
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.NPC2)
mySprite4 = sprites.create(img("""
        ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.NPC3)
mySprite5 = sprites.create(img("""
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.NPC4)
mySprite6 = sprites.create(img("""
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ....7.fd11111111df......
        ...7..fd11111111df......
        ...7..fd11111111df......
        ...7..fddd1111dddff.....
        ...77.fbdbfddfbdbfcf....
        ...777fcdcf11fcdcfbf....
        ....77fffbdb1bdffcf.....
        ....fcb1bcffffff........
        ....f1c1c1ffffff........
        ....fdfdfdfffff.........
        .....f.f.f..............
        ........................
        ........................
        ........................
        """),
    SpriteKind.NPC5)
mySprite7 = sprites.create(img("""
        ........................
        ........................
        ...........ccc..........
        ...........cccc.........
        .......ccc..ccccccc.....
        .......cccccc555555cc...
        ........ccb5555555555c..
        .....cc..b555555555555c.
        .....cccb555555ff155555c
        ......cb55555555ff55d55c
        ......b5555555555555555c
        ...cc.b555dd5555bb13bbc.
        ...cccd55ddddd555b3335c.
        .....bdddddddddd55b335c.
        ..cccdddddb55bbddd5555c.
        ..cccdddddb555bbbbcccc..
        ...ccddddddb5555cbcdc...
        ccccbdddddd5cb55cbcc....
        cddddddddd5555ccbbc.....
        .cddddddbdd555bbbcc.....
        ..ccdddbbbdd55cbcdc.....
        ....ccbbcbddddccdddcc...
        ......cccdd555dcccccc...
        ........cccccccc........
        """),
    SpriteKind.NPC6)
tiles.place_on_tile(mySprite7, tiles.get_tile_location(3, 14))
tiles.place_on_tile(mySprite6, tiles.get_tile_location(3, 9))
tiles.place_on_tile(mySprite5, tiles.get_tile_location(1, 5))
tiles.place_on_tile(mySprite4, tiles.get_tile_location(5, 3))
tiles.place_on_tile(mySprite2, tiles.get_tile_location(13, 8))
tiles.place_on_tile(mySprite3, tiles.get_tile_location(9, 3))
tiles.place_on_random_tile(mySprite, sprites.dungeon.collectible_blue_crystal)
scene.camera_follow_sprite(mySprite)
DialogMode = False
info.start_countdown(120)

def on_forever():
    if DialogMode == False:
        controller.move_sprite(mySprite)
    elif DialogMode == True:
        controller.move_sprite(mySprite, 0, 0)
    else:
        pass
forever(on_forever)
