namespace SpriteKind {
    export const NPC1 = SpriteKind.create()
    export const selesai = SpriteKind.create()
    export const NPC2 = SpriteKind.create()
    export const NPC3 = SpriteKind.create()
    export const NPC4 = SpriteKind.create()
    export const NPC5 = SpriteKind.create()
    export const NPC6 = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC2, function (sprite2, otherSprite2) {
    DialogMode = true
    game.showLongText("Dalam UUD NRI Tahun 1945 dari Pasal 27-Pasal 34 berisi tentang .... warga negara.", DialogLayout.Bottom)
    story.showPlayerChoices("Hak", "Kewajiban", "Tugas")
    if (story.checkLastAnswer("Hak")) {
        info.changeScoreBy(10)
        mySprite3.setKind(SpriteKind.selesai)
    } else if (story.checkLastAnswer("Kewajiban")) {
        info.changeScoreBy(-5)
    } else if (story.checkLastAnswer("Tugas")) {
        info.changeScoreBy(-5)
    } else {
    	
    }
    DialogMode = false
    pause(1000)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC1, function (sprite5, otherSprite5) {
    DialogMode = true
    game.showLongText("Apa contoh dari wujud hubungan aktif dari hubungan antara negara dengan warga negara ? ", DialogLayout.Bottom)
    story.showPlayerChoices("memberikan hak pilih dalam pemilu", "menaati peraturan lalu lintas ", "membayar pajak ")
    if (story.checkLastAnswer("memberikan hak pilih dalam pemilu")) {
        info.changeScoreBy(10)
        mySprite2.setKind(SpriteKind.selesai)
    } else if (story.checkLastAnswer(" menaati peraturan lalu lintas ")) {
        info.changeScoreBy(-5)
    } else if (story.checkLastAnswer("membayar pajak ")) {
        info.changeScoreBy(-5)
    } else {
    	
    }
    DialogMode = false
    pause(1000)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC5, function (sprite, otherSprite) {
    DialogMode = true
    game.showLongText("Bagaimana sifat hubungan antara negara dan warga negara ?", DialogLayout.Bottom)
    story.showPlayerChoices("Hubungan yang bersifat pasif", " Hubungan yang bersifat monopoli", "Hubungan yang bersifat totalitas")
    if (story.checkLastAnswer("Hubungan yang bersifat pasif")) {
        info.changeScoreBy(-5)
    } else if (story.checkLastAnswer(" Hubungan yang bersifat monopoli")) {
        info.changeScoreBy(-5)
    } else if (story.checkLastAnswer("Hubungan yang bersifat totalitas")) {
        info.changeScoreBy(10)
        mySprite6.setKind(SpriteKind.selesai)
    } else {
    	
    }
    DialogMode = false
    pause(1000)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC4, function (sprite4, otherSprite4) {
    DialogMode = true
    game.showLongText("Dibawah ini yang bukan merupakan asas hubungan warga negara dengan negara adalah...", DialogLayout.Bottom)
    story.showPlayerChoices("Pancasila ", "Pembukaan UUD 1945 alinea I dan II", "Pembukaan UUD 1945 alinea III dan IV")
    if (story.checkLastAnswer("Pancasila ")) {
        info.changeScoreBy(-5)
    } else if (story.checkLastAnswer("Pembukaan UUD 1945 alinea I dan II")) {
        info.changeScoreBy(10)
        mySprite5.setKind(SpriteKind.selesai)
    } else if (story.checkLastAnswer("Pembukaan UUD 1945 alinea III dan IV")) {
        info.changeScoreBy(-5)
    } else {
    	
    }
    DialogMode = false
    pause(1000)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC3, function (sprite3, otherSprite3) {
    DialogMode = true
    game.showLongText("Hak dan Kewajiban telah dicantumkan dalam UUD 1945 pasal. pasal berapa sajakah yang megatur mengenai hak dan kewajiban warga negara? ", DialogLayout.Bottom)
    story.showPlayerChoices("Pasal 25, 26, 27", "Pasal 30, 31, 32", "Pasal 27, 28, 30")
    if (story.checkLastAnswer("Pasal 25, 26, 27")) {
        info.changeScoreBy(-10)
    } else if (story.checkLastAnswer("Pasal 30, 31, 32")) {
        info.changeScoreBy(-10)
    } else if (story.checkLastAnswer("Pasal 27, 28, 30")) {
        info.changeScoreBy(30)
        mySprite4.setKind(SpriteKind.selesai)
    } else {
    	
    }
    DialogMode = false
    pause(1000)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC6, function (sprite6, otherSprite6) {
    DialogMode = true
    game.showLongText("Menurut teori Marxis, bagaimana pandangan terhadap peran negara dalam hubungannya dengan kaum borjuis?", DialogLayout.Bottom)
    story.showPlayerChoices("Negara hanya alat masyarakat", "Negara memiliki kekuatan nyata", "Negara harus dikendalikan oleh kelompok borjuis")
    if (story.checkLastAnswer("Negara hanya alat masyarakat")) {
        info.changeScoreBy(30)
        mySprite7.setKind(SpriteKind.selesai)
    } else if (story.checkLastAnswer("Negara memiliki kekuatan nyata")) {
        info.changeScoreBy(-10)
    } else if (story.checkLastAnswer("Negara harus dikendalikan oleh kelompok borjuis")) {
        info.changeScoreBy(-10)
    } else {
    	
    }
    DialogMode = false
    pause(1000)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleRedCrystal, function (sprite7, location) {
    game.over(true, effects.smiles)
})
let DialogMode = false
let mySprite7: Sprite = null
let mySprite6: Sprite = null
let mySprite5: Sprite = null
let mySprite4: Sprite = null
let mySprite3: Sprite = null
let mySprite2: Sprite = null
tiles.setTilemap(tilemap`level1`)
let mySprite = sprites.create(assets.image`princessFront0`, SpriteKind.Player)
mySprite2 = sprites.create(img`
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff......ccc.
    .ffefbf44fbfeff....cddc.
    .ffefbf44fbfeff...cddc..
    .fee4dddddd4eef.ccddc...
    fdfeeddddd4eeffecddc....
    fbffee4444ee4fddccc.....
    fbf4f222222f1edde.......
    fcf.f222222f44ee........
    .ff.f445544f............
    ....ffffffff............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.NPC1)
mySprite3 = sprites.create(img`
    ........................
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff..........
    .ffefbf44fbfeff.........
    .fee41fddf14eef.........
    fdfeeddddd4eff..........
    fbffee444edd4e..........
    fbf4f2222edde...........
    fcf.f22cccee............
    .ff.f44cdc4f............
    ....fffddcff............
    .....fddcff.............
    ....cddc................
    ....cdc.................
    ....cc..................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.NPC2)
mySprite4 = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.NPC3)
mySprite5 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.NPC4)
mySprite6 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ....7.fd11111111df......
    ...7..fd11111111df......
    ...7..fd11111111df......
    ...7..fddd1111dddff.....
    ...77.fbdbfddfbdbfcf....
    ...777fcdcf11fcdcfbf....
    ....77fffbdb1bdffcf.....
    ....fcb1bcffffff........
    ....f1c1c1ffffff........
    ....fdfdfdfffff.........
    .....f.f.f..............
    ........................
    ........................
    ........................
    `, SpriteKind.NPC5)
mySprite7 = sprites.create(img`
    ........................
    ........................
    ...........ccc..........
    ...........cccc.........
    .......ccc..ccccccc.....
    .......cccccc555555cc...
    ........ccb5555555555c..
    .....cc..b555555555555c.
    .....cccb555555ff155555c
    ......cb55555555ff55d55c
    ......b5555555555555555c
    ...cc.b555dd5555bb13bbc.
    ...cccd55ddddd555b3335c.
    .....bdddddddddd55b335c.
    ..cccdddddb55bbddd5555c.
    ..cccdddddb555bbbbcccc..
    ...ccddddddb5555cbcdc...
    ccccbdddddd5cb55cbcc....
    cddddddddd5555ccbbc.....
    .cddddddbdd555bbbcc.....
    ..ccdddbbbdd55cbcdc.....
    ....ccbbcbddddccdddcc...
    ......cccdd555dcccccc...
    ........cccccccc........
    `, SpriteKind.NPC6)
tiles.placeOnTile(mySprite7, tiles.getTileLocation(3, 14))
tiles.placeOnTile(mySprite6, tiles.getTileLocation(3, 9))
tiles.placeOnTile(mySprite5, tiles.getTileLocation(1, 5))
tiles.placeOnTile(mySprite4, tiles.getTileLocation(5, 3))
tiles.placeOnTile(mySprite2, tiles.getTileLocation(13, 8))
tiles.placeOnTile(mySprite3, tiles.getTileLocation(9, 3))
tiles.placeOnRandomTile(mySprite, sprites.dungeon.collectibleBlueCrystal)
scene.cameraFollowSprite(mySprite)
DialogMode = false
info.startCountdown(120)
forever(function () {
    if (DialogMode == false) {
        controller.moveSprite(mySprite)
    } else if (DialogMode == true) {
        controller.moveSprite(mySprite, 0, 0)
    } else {
    	
    }
})
